route: 
  group_by: ['alertname']       
  group_wait: 30s              
  group_interval: 5m          
  repeat_interval: 1h        
  receiver: 'web.hook'      

  routes:                  
    - match_re:           
        job: (prometheus|Prometheus|Production|Deployment|Jenkins|Nexus_Sonar|Harbor|Harbor_Docker|Deployment_Docker|Production_Dokcer|Harbor_cAdvisor|Deployment_cAdvisor|Production_cAdvisor)
      group_by: ['team', 'env'] 
      receiver: slack    

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/' # webhook endpoint

  - name: slack
    slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#java_application_tm'
        title: '{{ .GroupLabels.team }} has alerts in env: {{ .GroupLabels.env }}'
        text: '{{ range .Alerts }}{{ .Annotations.message }}{{ "\n" }}{{ end }}' # list all messages

inhibit_rules:
  - source_match:
      severity: 'critical'      # if critical alert fires
    target_match:
      severity: 'warning'       # silence related warnings
    equal: ['alertname', 'dev', 'instance'] # only if these labels match
